#!/bin/bash




error()
{
	if [ $1 -ne 0 ]
	then
		echo "Copying the project to tools directory failed"
		exit 3
	fi
}




ls -la ~/tools > /dev/null 2>&1
if [ $? -ne 0 ]
then
	mkdir -p ~/tools
fi

# Copying the project to tools directory
cp -r ./project/* ~/tools > /dev/null 2>&1

error $?

