#!/bin/bash

ls -la ~/tools/project/assests/  > /dev/null 2>&1



error()
{
	if [ $1 -ne 0 ]
	then
		echo "Copying the project to tools directory failed"
		exit 3
	fi
}




if [ $? -ne 0 ]
then
	mkdir -p ~/tools/project/assests
fi

# Copying the project to tools directory
cp -r ./project/ ~/tools > /dev/null 2>&1
error $?

