#!/bin/bash

error()
{
	if [ $1 -ne 0 ]
	then
		echo "ERROR : $2"
		exit 3
	fi
}

C=""
P=`pwd`
## check_permasion that teke from user to delet oll folder
check_permasion()
{
	read C
	if [[ $C != YES && $C != Y && $C != yes && $C != y && $C != "" ]] 
	then
		if [[ $C == NO || $C == N || $C == no || $C == n  ]]
		then
			echo "alright next time"
			exit 0
		fi
		check_permasion
	fi
}


ls -la ~/tools/project/assests/  > /dev/null 2>&1
error $? "FILE not found"
echo "All files in folder will be deleted expect the hidden files"
echo "yes / no | Y/n ?"

A=`ls | xargs echo -n`
if [[ $A != "" ]]
then
	check_permasion
fi

# remove the files in directory
find -not -path '*/.*' -delete > /dev/null 2>&1
error $? "remove files in directory failed"


# copy assests to the project directory
cp -r ~/tools/project/assests/* $P > /dev/null 2>&1
error $? "copy assests failed"